### ISSUE TITLE
Test error at org.joda.convert.test1.Test1Class

### ISSUE THREAD

**Issue by a17r** [JodaOrg/joda-convert#11]
Am I the only one who can't get that test to succeed?

java version "1.7.0_75"
OpenJDK Runtime Environment (IcedTea 2.5.4) (Gentoo package icedtea-7.2.5.4)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)

    [junit] Running org.joda.convert.test1.Test1Class
    [junit] Testsuite: org.joda.convert.test1.Test1Class
    [junit] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0,147 sec
    [junit] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0,147 sec
    [junit] 
    [junit] Testcase: initializationError took 0,008 sec
    [junit]     Caused an ERROR
    [junit] Test class should have exactly one public zero-argument constructor
    [junit] java.lang.Exception: Test class should have exactly one public zero-argument constructor
    [junit]     at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    [junit] 
    [junit] Testcase: initializationError took 0,001 sec
    [junit]     Caused an ERROR
    [junit] No runnable methods
    [junit] java.lang.Exception: No runnable methods
    [junit]     at java.lang.reflect.Constructor.newInstance(Constructor.java:526)

**Comment by jodastephen** [comment]
Not sure how you are running, but that class is not a test.

**Comment by a17r** [comment]
Hmm sorry, I'll need to take a closer look at why the build system does what it does... my Java is a bit rusty.
