### ISSUE TITLE
Superclass-searching in findAnyConverter results in invalid conversions

### ISSUE THREAD

**Issue by mdekstrand** [JodaOrg/joda-convert#15]
**Observed symptom**

Iit is possible for the following code:

```java
converter.convertFromString(Foo.class, "foo-repr")
```

to result in an object that is not an instance of `Foo`.

**Cause**

When `StringConvert` searches for a converter, it first searches for a registered converter for `Foo`. If it does not find one, it then begins searching for converters for `Foo`'s superclasses.

This is correct when doing a conversion *from* a `Foo`. However, when converting *to* a `Foo`, it is only correct to use a converter for a *subclass* of `Foo`. A supertype converter may not convert to `Foo`.

**Context**

Found when attempting to use joda-convert to convert to a custom implementation of `CharSequence`. The default-registered `CharSequence` converter just casts a string, which is not an instance of my custom `CharSequence`. Since `StringConvert.INSTANCE` is also immutable, I cannot register a custom converter in a static initializer block to enable seamless conversions.

**Comment by jodastephen** [comment]
Can you paste in a shortened form of the converter you tried just to help me formulate tests. Not sure what the implications of this are yet. thanks

**Comment by mdekstrand** [comment]
@jodastephen The full class, including the `@FromString` method, is here: https://github.com/mdekstrand/lenskit/blob/graveyard/text-charseq/lenskit-core/src/main/java/org/lenskit/util/Text.java

(Implementing `CharSequence` is a bit obnoxious, but anything that implements it should exhibit the same problem).

**Comment by jodastephen** [comment]
Taking a look, I think the only sensible option is to remove the superclass searching. Do you agree? (see the linked commit above)

**Comment by mdekstrand** [comment]
@jodastephen I agree. If searching was available separately for to/from string converters, then it could be kept for the appropriate one, but for bidirectional conversions turning it off is the appropriate solution.

Code that breaks can always register converters for its particular classes.
