### ISSUE TITLE
Fails with 'Two methods are annotated' when the `@ToString` method is a specific implementation of a generic interface

### ISSUE THREAD

**Issue by hackmann** [JodaOrg/joda-convert#23]
Generic interface
```java
public interface HasCode<C> {
    C getCode();
}
```
And a String implementation
```java
public final class AirportCode implements HasCode<String> {
    private final String code;

    @Override
    @ToString
    public String getCode() {
        return code;
    }

```
It fails with 'Two methods are annotated with @ToString: net.worldticket.commons.flight.AirportCode.'

It finds the `getCode()` method twice one with a String return type and the other with an Object as return type.

**Comment by jodastephen** [comment]
Looks like the [compiler changed](https://bugs.openjdk.java.net/browse/JDK-6695379) although I can't reproduce it.
