### ISSUE TITLE
String replacement doesn't work

### ISSUE THREAD

**Issue by sormuras** [JodaOrg/joda-convert#25]
The published POM contains many ${joda.artifactId} snippets.

http://central.maven.org/maven2/org/joda/joda-convert/2.0.1/joda-convert-2.0.1.pom

```xml
...
<artifactId>joda-convert</artifactId>
<packaging>jar</packaging>
<name>Joda-Convert</name>
<version>2.0.1</version>
<description>Library to convert Objects to and from String</description>
<url>http://www.joda.org/${joda.artifactId}/</url>
...
```

**Comment by jodastephen** [comment]
I don't see why that is a problem - its just normal Maven behaviour. That file is the pom.xml as seen in the project. If maven interprets it, the variables will be resolved.

**Comment by sormuras** [comment]
True.

But if you grab the value _as-is_ you no longer get the final expanded value. 

Version `1.9.2` of the `pom.xml` declared `<url>http://www.joda.org/joda-convert/</url>` ... which is directly useable from scanners like [jpms-module-names](https://github.com/jodastephen/jpms-module-names/blob/master/generated/modules.md#joda) ... which don't use "normal" Maven/Aether API to retrieve values from the poms.

**Comment by jodastephen** [comment]
Unfortunately this is just the way Maven works. See [here](http://central.maven.org/maven2/org/apache/commons/commons-lang3/3.7/commons-lang3-3.7.pom) for example

**Comment by sormuras** [comment]
Sure. But `${...}` is seldom used in the **URL** element. Older versions of your libraries don't do it. All other libraries included in the `jpms-module-names` table don't do it.

This is 100% an issue of the `jpms-module-names` -- thus, I'm closing this and https://github.com/JodaOrg/joda-beans/issues/189

**Comment by jodastephen** [comment]
I'm introducing a parent pom, so all joda-projects will likely have this over time!

**Comment by sormuras** [comment]
_I saw it coming..._ 🙈

**Comment by sormuras** [comment]
...maybe, I'll enhance the XML/POM parser to look for local properties:

```xml
<properties>
<!--  Parent pom.xml control  -->
<joda.osgi.packages>org.joda.convert.*</joda.osgi.packages>
<joda.module.name>org.joda.convert</joda.module.name>
<joda.artifactId>joda-convert</joda.artifactId>
<!--  Set to Java 6  -->
<joda.release.version>6</joda.release.version>
<maven.compiler.compilerVersion>1.6</maven.compiler.compilerVersion>
<maven.compiler.source>1.6</maven.compiler.source>
<maven.compiler.target>1.6</maven.compiler.target>
</properties>
```

**Comment by sormuras** [comment]
Done in https://github.com/jodastephen/jpms-module-names/commit/692be4f313a05032c42ba49dfe996677c358cc03

**Comment by jodastephen** [comment]
Great!
