### ISSUE TITLE
Remove reference to javax.xml.bind.DatatypeConverter

### ISSUE THREAD

**Issue by dlew** [JodaOrg/joda-convert#7]
Not strictly necessary, but Android doesn't include javax.xml.bind so if this were removed it would be easier to include this lib in Android without it complaining.

**Comment by tomball** [comment]
Does the output have to be Base64? I can't find an output format specified anywhere. If doesn't matter, would your org.joda.convert.factory.ByteObjectArrayStringConverterFactory work? It's not as compact a format, but already meets your authorship/license requirements.

**Comment by jodastephen** [comment]
I've implemented a Base64 encode/decode

**Comment by tomball** [comment]
Thanks! It helps iOS users, too:

```sh
$ j2objc -d /tmp/joda -classpath ~/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar -sourcepath src/main/java `find src/main/java -name *.java`
translating src/main/java/org/joda/convert/AbstractTypeStringConverter.java
translating src/main/java/org/joda/convert/AnnotationStringConverterFactory.java
translating src/main/java/org/joda/convert/EnumStringConverterFactory.java
translating src/main/java/org/joda/convert/factory/BooleanArrayStringConverterFactory.java
translating src/main/java/org/joda/convert/factory/BooleanObjectArrayStringConverterFactory.java
translating src/main/java/org/joda/convert/factory/ByteObjectArrayStringConverterFactory.java
translating src/main/java/org/joda/convert/factory/CharObjectArrayStringConverterFactory.java
translating src/main/java/org/joda/convert/factory/NumericArrayStringConverterFactory.java
translating src/main/java/org/joda/convert/factory/NumericObjectArrayStringConverterFactory.java
translating src/main/java/org/joda/convert/FromString.java
translating src/main/java/org/joda/convert/FromStringConverter.java
translating src/main/java/org/joda/convert/FromStringFactory.java
translating src/main/java/org/joda/convert/JDKStringConverter.java
translating src/main/java/org/joda/convert/MethodConstructorStringConverter.java
translating src/main/java/org/joda/convert/MethodsStringConverter.java
translating src/main/java/org/joda/convert/ReflectionStringConverter.java
translating src/main/java/org/joda/convert/RenameHandler.java
translating src/main/java/org/joda/convert/StringConvert.java
translating src/main/java/org/joda/convert/StringConverter.java
translating src/main/java/org/joda/convert/StringConverterFactory.java
translating src/main/java/org/joda/convert/ToString.java
translating src/main/java/org/joda/convert/ToStringConverter.java
translating src/main/java/org/joda/convert/TypedAdapter.java
translating src/main/java/org/joda/convert/TypedStringConverter.java
translating src/main/java/org/joda/convert/TypeStringConverter.java
translating src/main/java/org/joda/convert/TypeTokenStringConverter.java
Translated 26 files: 0 errors, 0 warnings
```

There are a few test failures, which are likely due to problems with j2objc's JRE emulation.

**Comment by advayDev1** [comment]
@jodastephen would it be possible to get an official release on Maven Central with this fix 962dd4c?

We are trying to get joda-convert easily usable in Gradle projects shared across Android and iOS, and this commit is currently the blocker:
https://travis-ci.org/j2objc-contrib/j2objc-common-libs-e2e-test/jobs/82347638

Thanks!

**Comment by brunobowden** [comment]
@jodastphen - Thanks for your work on this. Can I echo the request from @advayDev1 for an official release with the fix. This'll make it much easier to use it on iOS using Google's J2ObjC (Java to Objective-C translator).

**Comment by brunobowden** [comment]
Corrected name:

@jodastephen - Thanks for your work on this. Can I echo the request from @advayDev1 for an official release with the fix. This'll make it much easier to use it on iOS using Google's J2ObjC (Java to Objective-C translator).

**Comment by jodastephen** [comment]
v1.8 released

**Comment by brunobowden** [comment]
@jodastephen - thanks for the new release.

@advayDev1 - let's give this a whirl...
